[package]
name = "console_tools"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hello"
path = "src/bin/hello.rs"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
colored = "2.0.4"
